### ISSUE TITLE
Can't add property sourceDirectories, object is not extensible

### ISSUE THREAD

**Issue by nightire** [ember-cli/ember-cli-lodash-subset#30]
```text
ember-cli: 2.9.1
node: 6.9.1
npm: 3.10.9
os: darwin x64
```

```text
Can't add property sourceDirectories, object is not extensible
TypeError: Can't add property sourceDirectories, object is not extensible
    at c (/Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:625)
    at Gt (/Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:10644)
    at /Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:12116
    at /Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:3114
    at ur (/Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:11997)
    at $r (/Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:15018)
    at or (/Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:11685)
    at /Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:12038
    at /Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:3114
    at ur (/Users/nightire/Code/qui.cform.io/node_modules/ember-cli-lodash-subset/index.js:1:11997)
```

**Comment by stefanpenner** [comment]
can you share a reproduction, CI seems to think this is fine?

**Comment by nightire** [comment]
@stefanpenner Sure, I put this addon on github at: https://github.com/nightire/ember-cform-ui

This was happened after we upgrade ember-cli to v2.9.1, we follow the release note strictly.

BTW, we also had upgraded other ember app and ember addons we currently working on, only this one got the problem, I try to copy ember-cli-lodash-subset from other project to this addon, but it still throw the same error.

**Comment by nightire** [comment]
@stefanpenner Hi, I have same repo in another machine with same environment, and it works fine. So I try to rename the old `node_modules` and install npm modules again, then I can reproduce the problem. Below is the diff for two `node_modules` directory, I grep the result so only files missing in one of them listed, does it help?

``` text
$ diff -rq node_modules/ _node_modules/ | grep Only
Only in node_modules/: babel-code-frame
Only in node_modules/babel-core: node_modules
Only in _node_modules/broccoli-caching-writer: node_modules
Only in node_modules/broccoli-concat/node_modules: broccoli-kitchen-sink-helpers
Only in node_modules/broccoli-config-replace/node_modules: broccoli-kitchen-sink-helpers
Only in node_modules/broccoli-config-replace/node_modules: broccoli-plugin
Only in node_modules/broccoli-filter: node_modules
Only in _node_modules/broccoli-funnel/node_modules: minimatch
Only in node_modules/broccoli-funnel/node_modules: walk-sync
Only in node_modules/broccoli-kitchen-sink-helpers: .gittags.rb
Only in node_modules/broccoli-persistent-filter: node_modules
Only in node_modules/broccoli-plugin: .gittags.rb
Only in node_modules/broccoli-plugin: .jshintignore
Only in node_modules/broccoli-plugin: .jshintrc
Only in node_modules/broccoli-plugin: .npmignore
Only in node_modules/broccoli-plugin: .travis.yml
Only in node_modules/broccoli-plugin: test
Only in _node_modules/broccoli-stew/node_modules: minimatch
Only in node_modules/broccoli-stew/node_modules: walk-sync
Only in node_modules/broccoli-uglify-sourcemap/node_modules: broccoli-plugin
Only in node_modules/detect-indent: node_modules
Only in _node_modules/: ember-autoresize
Only in _node_modules/ember-cli/node_modules: minimatch
Only in node_modules/ember-cli/node_modules: walk-sync
Only in node_modules/ember-cli-eslint: node_modules
Only in node_modules/ember-cli-node-assets/node_modules/lodash: _getRawTag.js
Only in node_modules/ember-cli-node-assets/node_modules/lodash: _objectToString.js
Only in node_modules/ember-cli-preprocess-registry/node_modules/lodash: _getRawTag.js
Only in node_modules/ember-cli-preprocess-registry/node_modules/lodash: _objectToString.js
Only in node_modules/ember-cli-surge/node_modules/lodash: _getRawTag.js
Only in node_modules/ember-cli-surge/node_modules/lodash: _objectToString.js
Only in node_modules/ember-try: .idea
Only in node_modules/ember-try: appveyor.yml
Only in node_modules/ember-try: fail-if-no-foo.sh
Only in node_modules/ember-try-config/node_modules/lodash: _getRawTag.js
Only in node_modules/ember-try-config/node_modules/lodash: _objectToString.js
Only in node_modules/eslint/lib/formatters: codeframe.js
Only in node_modules/eslint/lib/rules: no-useless-return.js
Only in node_modules/eslint/node_modules/lodash: _getRawTag.js
Only in node_modules/eslint/node_modules/lodash: _objectToString.js
Only in _node_modules/eslint/node_modules: minimatch
Only in node_modules/external-editor: node_modules
Only in _node_modules/fireworm/node_modules: minimatch
Only in node_modules/fstream-ignore: node_modules
Only in _node_modules/globby/node_modules: minimatch
Only in node_modules/hash-for-dep: node_modules
Only in node_modules/inline-source-map-comment: node_modules
Only in node_modules/inquirer/node_modules/lodash: _getRawTag.js
Only in node_modules/inquirer/node_modules/lodash: _objectToString.js
Only in node_modules/: interpret
Only in _node_modules/matcher-collection: node_modules
Only in _node_modules/minimatch: browser.js
Only in _node_modules/minimist/test: all_bool.js
Only in _node_modules/minimist/test: bool.js
Only in _node_modules/minimist/test: kv_short.js
Only in _node_modules/minimist/test: num.js
Only in _node_modules/minimist/test: stop_early.js
Only in _node_modules/minimist/test: unknown.js
Only in _node_modules/mkdirp: node_modules
Only in node_modules/node-notifier/node_modules: minimist
Only in _node_modules/optimist: node_modules
Only in node_modules/: rechoir
Only in _node_modules/rimraf/node_modules: minimatch
Only in _node_modules/sane/node_modules: minimatch
Only in node_modules/sane/node_modules: minimist
Only in node_modules/shelljs: .editorconfig
Only in node_modules/shelljs: .eslintrc.json
Only in node_modules/shelljs: CHANGELOG.md
Only in node_modules/shelljs: node_modules
Only in node_modules/shelljs: plugin.js
Only in node_modules/shelljs/src: head.js
Only in node_modules/shelljs/src: sort.js
Only in node_modules/shelljs/src: tail.js
Only in node_modules/shelljs/src: uniq.js
Only in node_modules/table/node_modules/lodash: _getRawTag.js
Only in node_modules/table/node_modules/lodash: _objectToString.js
Only in _node_modules/testem/node_modules: minimatch
Only in _node_modules/tree-sync: node_modules
Only in _node_modules/walk-sync: README.md
```

`_node_modules` is the old one, and `node_modules` is the one has problem.

**Comment by stefanpenner** [comment]
~~Interestingly it seems that removing `ember-cli-eslint`mitigates the issue...~~ Still not quite sure why this is happening.

`yarn install` seems to work :trollface:

**Comment by nightire** [comment]
Damn! `yarn` did works! Let's blame npm for now...

**Comment by stefanpenner** [comment]
> Let's blame npm for now...

Sounds fair :P

Although something clearly is wrong, we should likely try and figure out what. I need to find some more time to dig in further....

I actually dont think the issue is with this repo directly, rather in some other part of the system but it manifests here. But until we know where, this may be the appropriate place to keep this issue.
